/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppLayoutRouteImport } from './routes/app/_appLayout'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as AppAppLayoutIndexRouteImport } from './routes/app/_appLayout.index'
import { Route as AppAppLayoutShadcnTestRouteImport } from './routes/app/_appLayout.shadcn-test'
import { Route as AppAppLayoutReportRouteImport } from './routes/app/_appLayout.report'
import { Route as AppAppLayoutProfileRouteImport } from './routes/app/_appLayout.profile'
import { Route as AppAppLayoutAnimalsRouteImport } from './routes/app/_appLayout.animals'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users.$userId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRouteImport = createFileRoute('/app')()

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppLayoutRoute = AppAppLayoutRouteImport.update({
  id: '/_appLayout',
  getParentRoute: () => AppRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppLayoutIndexRoute = AppAppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppLayoutRoute,
} as any)
const AppAppLayoutShadcnTestRoute = AppAppLayoutShadcnTestRouteImport.update({
  id: '/shadcn-test',
  path: '/shadcn-test',
  getParentRoute: () => AppAppLayoutRoute,
} as any)
const AppAppLayoutReportRoute = AppAppLayoutReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppAppLayoutRoute,
} as any)
const AppAppLayoutProfileRoute = AppAppLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAppLayoutRoute,
} as any)
const AppAppLayoutAnimalsRoute = AppAppLayoutAnimalsRouteImport.update({
  id: '/animals',
  path: '/animals',
  getParentRoute: () => AppAppLayoutRoute,
} as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/app': typeof AppAppLayoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/app/animals': typeof AppAppLayoutAnimalsRoute
  '/app/profile': typeof AppAppLayoutProfileRoute
  '/app/report': typeof AppAppLayoutReportRoute
  '/app/shadcn-test': typeof AppAppLayoutShadcnTestRoute
  '/app/': typeof AppAppLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/app': typeof AppAppLayoutIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/app/animals': typeof AppAppLayoutAnimalsRoute
  '/app/profile': typeof AppAppLayoutProfileRoute
  '/app/report': typeof AppAppLayoutReportRoute
  '/app/shadcn-test': typeof AppAppLayoutShadcnTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/app/_appLayout': typeof AppAppLayoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/app/_appLayout/animals': typeof AppAppLayoutAnimalsRoute
  '/app/_appLayout/profile': typeof AppAppLayoutProfileRoute
  '/app/_appLayout/report': typeof AppAppLayoutReportRoute
  '/app/_appLayout/shadcn-test': typeof AppAppLayoutShadcnTestRoute
  '/app/_appLayout/': typeof AppAppLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/api/users'
    | '/app'
    | '/api/auth/$'
    | '/api/users/$userId'
    | '/app/animals'
    | '/app/profile'
    | '/app/report'
    | '/app/shadcn-test'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api/users'
    | '/app'
    | '/api/auth/$'
    | '/api/users/$userId'
    | '/app/animals'
    | '/app/profile'
    | '/app/report'
    | '/app/shadcn-test'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/api/users'
    | '/app'
    | '/app/_appLayout'
    | '/api/auth/$'
    | '/api/users/$userId'
    | '/app/_appLayout/animals'
    | '/app/_appLayout/profile'
    | '/app/_appLayout/report'
    | '/app/_appLayout/shadcn-test'
    | '/app/_appLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_appLayout': {
      id: '/app/_appLayout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_appLayout/': {
      id: '/app/_appLayout/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppLayoutIndexRouteImport
      parentRoute: typeof AppAppLayoutRoute
    }
    '/app/_appLayout/shadcn-test': {
      id: '/app/_appLayout/shadcn-test'
      path: '/shadcn-test'
      fullPath: '/app/shadcn-test'
      preLoaderRoute: typeof AppAppLayoutShadcnTestRouteImport
      parentRoute: typeof AppAppLayoutRoute
    }
    '/app/_appLayout/report': {
      id: '/app/_appLayout/report'
      path: '/report'
      fullPath: '/app/report'
      preLoaderRoute: typeof AppAppLayoutReportRouteImport
      parentRoute: typeof AppAppLayoutRoute
    }
    '/app/_appLayout/profile': {
      id: '/app/_appLayout/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppAppLayoutProfileRouteImport
      parentRoute: typeof AppAppLayoutRoute
    }
    '/app/_appLayout/animals': {
      id: '/app/_appLayout/animals'
      path: '/animals'
      fullPath: '/app/animals'
      preLoaderRoute: typeof AppAppLayoutAnimalsRouteImport
      parentRoute: typeof AppAppLayoutRoute
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiUsersRouteChildren {
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersUserIdRoute: ApiUsersUserIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

interface AppAppLayoutRouteChildren {
  AppAppLayoutAnimalsRoute: typeof AppAppLayoutAnimalsRoute
  AppAppLayoutProfileRoute: typeof AppAppLayoutProfileRoute
  AppAppLayoutReportRoute: typeof AppAppLayoutReportRoute
  AppAppLayoutShadcnTestRoute: typeof AppAppLayoutShadcnTestRoute
  AppAppLayoutIndexRoute: typeof AppAppLayoutIndexRoute
}

const AppAppLayoutRouteChildren: AppAppLayoutRouteChildren = {
  AppAppLayoutAnimalsRoute: AppAppLayoutAnimalsRoute,
  AppAppLayoutProfileRoute: AppAppLayoutProfileRoute,
  AppAppLayoutReportRoute: AppAppLayoutReportRoute,
  AppAppLayoutShadcnTestRoute: AppAppLayoutShadcnTestRoute,
  AppAppLayoutIndexRoute: AppAppLayoutIndexRoute,
}

const AppAppLayoutRouteWithChildren = AppAppLayoutRoute._addFileChildren(
  AppAppLayoutRouteChildren,
)

interface AppRouteChildren {
  AppAppLayoutRoute: typeof AppAppLayoutRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAppLayoutRoute: AppAppLayoutRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
